import { NextRequest, NextResponse } from 'next/server';
import { verifyToken, generateKeyUrl } from '../../../../lib/auth';
import fs from 'fs';
import path from 'path';

export async function GET(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    const cookieToken = request.cookies.get('auth-token')?.value;
    const videoId = request.nextUrl.searchParams.get('videoId');
    const token = authHeader?.replace('Bearer ', '') || cookieToken;

    console.log('Auth header:', authHeader);
    console.log('Cookie token:', cookieToken);
    console.log('Final token:', token);

    if (!token) {
      console.log('No token provided');
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const user = verifyToken(token);
    if (!user) {
      console.log('Invalid token');
      return NextResponse.json({ error: 'Invalid authentication' }, { status: 401 });
    }

    console.log('User authenticated:', user.id);

    if (!videoId) {
      return NextResponse.json({ error: 'Video ID required' }, { status: 400 });
    }

    const keyUrl = generateKeyUrl(user.id);
    console.log('Generated key URL:', keyUrl);

    // Read the actual m3u8 file generated by FFmpeg (adjust path as needed)
    const playlistPath = path.join(process.cwd(), 'public', 'videos', `video-${videoId}`, 'playlist.m3u8');
    
    console.log('Looking for playlist at:', playlistPath);
    console.log('File exists:', fs.existsSync(playlistPath));
    
    let playlist: string;
    
    try {
      // Try to read the FFmpeg-generated playlist
      playlist = fs.readFileSync(playlistPath, 'utf8');
      
      // Update the key URL in the existing playlist
      playlist = playlist.replace(
        /#EXT-X-KEY:METHOD=AES-128,URI="[^"]*"/g,
        `#EXT-X-KEY:METHOD=AES-128,URI="${keyUrl}"`
      );
      
      // Update segment URLs to point to your API endpoints
      playlist = playlist.replace(
        /^segment(\d{3})\.ts$/gm,
        `/api/stream/segment$1.ts?videoId=${videoId}`
      );
      
    } catch (fileError) {
      console.log('Could not read FFmpeg playlist:', fileError);
      console.log('Trying to list directory contents...');
      
      const videoDir = path.join(process.cwd(), 'public', 'videos', `video-${videoId}`);
      try {
        const files = fs.readdirSync(videoDir);
        console.log('Files in video directory:', files);
      } catch (dirError) {
        console.log('Video directory does not exist:', videoDir);
        return NextResponse.json({ 
          error: 'Video not found',
          debug: { videoId, expectedPath: playlistPath }
        }, { status: 404 });
      }
      
      // Fallback: Generate playlist manually (ensure IV matches your enc.keyinfo)
      // Use the same IV you used in enc.keyinfo file
      playlist = `#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="${keyUrl}",IV=0x0123456789ABCDEF0123456789ABCDEF
#EXTINF:10.0,
/api/stream/segment000.ts?videoId=${videoId}
#EXTINF:10.0,
/api/stream/segment001.ts?videoId=${videoId}
#EXTINF:10.0,
/api/stream/segment002.ts?videoId=${videoId}
#EXTINF:10.0,
/api/stream/segment003.ts?videoId=${videoId}
#EXTINF:10.0,
/api/stream/segment004.ts?videoId=${videoId}
#EXTINF:10.0,
/api/stream/segment005.ts?videoId=${videoId}
#EXTINF:5.97,
/api/stream/segment006.ts?videoId=${videoId}
#EXT-X-ENDLIST`;
    }

    return new NextResponse(playlist, {
      headers: {
        'Content-Type': 'application/vnd.apple.mpegurl',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET',
        'Access-Control-Allow-Headers': 'Authorization, Content-Type',
        'Access-Control-Allow-Credentials': 'true',
      }
    });
  } catch (error) {
    console.error('Playlist generation error:', error);
    return NextResponse.json({ error: 'Failed to generate playlist' }, { status: 500 });
  }
}